POLICIES = {
    0: dict(
        allow_all=True,
        segmentation=False,
        authentication=False,
        role_authorization=False,
        attribute_based_access=False,
        microsegmentation=False,
        restrict_ping=False,
        idle_timeout=0,
        hard_timeout=0,
        reauth_interval=0,
        max_session_age=0,
    ),
    1: dict(
        allow_all=False,
        segmentation=True,
        authentication=False,
        role_authorization=False,
        attribute_based_access=False,
        microsegmentation=False,
        restrict_ping=False,
        idle_timeout=30,
        hard_timeout=30,
        reauth_interval=0,
        max_session_age=0,
    ),
    2: dict(
        allow_all=False,
        segmentation=True,
        authentication=True,
        role_authorization=True,
        attribute_based_access=False,
        microsegmentation=False,
        restrict_ping=False,
        idle_timeout=30,
        hard_timeout=15,
        reauth_interval=10,
        max_session_age=60,
    ),
    3: dict(
        allow_all=False,
        segmentation=True,
        authentication=True,
        role_authorization=True,
        attribute_based_access=True,
        microsegmentation=False,
        restrict_ping=False,
        idle_timeout=5,
        hard_timeout=5,
        reauth_interval=5,
        max_session_age=20,
    ),
    4: dict(
        allow_all=False,
        segmentation=True,
        authentication=True,
        role_authorization=True,
        attribute_based_access=True,
        microsegmentation=True,
        restrict_ping=True,
        idle_timeout=5,
        hard_timeout=5,
        reauth_interval=5,
        max_session_age=20,
    ),
}

ALLOWED_ROLES = {
    ("user", "app"),
    ("admin", "app"),
    ("admin", "db"),
    ("app", "db"),
    ("app", "admin"),
    ("db", "admin"),
}

ALLOWED_FLOWS = {
    ("10.0.1.11", "10.0.3.11", 443),
    ("10.0.1.12", "10.0.3.11", 443),
    ("10.0.1.13", "10.0.3.11", 443),
    ("10.0.2.11", "10.0.3.11", 443),
    ("10.0.2.11", "10.0.3.12", 22),
    ("10.0.3.11", "10.0.3.12", 5432),
}
