POLICIES = {
    0: dict(
        allow_all=True,
        segmentation=False,
        authentication=False,
        role_authorization=False,
        attribute_based_access=False,
        microsegmentation=False,
        restrict_ping=False,
        flow_idle_timeout=0,
        flow_hard_timeout=0,
        session_idle_timeout=0,
        session_reauth_interval=0,
        session_max_age=0,
    ),
    1: dict(
        allow_all=False,
        segmentation=True,
        authentication=False,
        role_authorization=False,
        attribute_based_access=False,
        microsegmentation=False,
        restrict_ping=False,
        flow_idle_timeout=30,
        flow_hard_timeout=60,
        session_idle_timeout=60,
        session_reauth_interval=0,
        session_max_age=0,
    ),
    2: dict(
        allow_all=False,
        segmentation=True,
        authentication=True,
        role_authorization=True,
        attribute_based_access=False,
        microsegmentation=False,
        restrict_ping=False,
        flow_idle_timeout=20,
        flow_hard_timeout=60,
        session_idle_timeout=60,
        session_reauth_interval=15,
        session_max_age=120,
    ),
    3: dict(
        allow_all=False,
        segmentation=True,
        authentication=True,
        role_authorization=True,
        attribute_based_access=True,
        microsegmentation=False,
        restrict_ping=False,
        flow_idle_timeout=10,
        flow_hard_timeout=30,
        session_idle_timeout=45,
        session_reauth_interval=10,
        session_max_age=30,
    ),
    4: dict(
        allow_all=False,
        segmentation=True,
        authentication=True,
        role_authorization=True,
        attribute_based_access=True,
        microsegmentation=True,
        restrict_ping=True,
        flow_idle_timeout=5,
        flow_hard_timeout=20,
        session_idle_timeout=30,
        session_reauth_interval=5,
        session_max_age=60,
    ),
}

ALLOWED_ROLES = {
    ("user", "app"),
    ("admin", "app"),
    ("admin", "db"),
    ("app", "db"),
    ("app", "admin"),
    ("db", "admin"),
}

ALLOWED_FLOWS = {
    ("10.0.1.11", "10.0.3.11", 443),
    ("10.0.1.12", "10.0.3.11", 443),
    ("10.0.1.13", "10.0.3.11", 443),
    ("10.0.2.11", "10.0.3.11", 443),
    ("10.0.2.11", "10.0.3.12", 22),
    ("10.0.3.11", "10.0.3.12", 5432),
}
